language: node_js
node_js:
- '0.10'
before_script:
- npm install -g bower
- bower install
- npm install -g grunt-cli
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- grunt
after_script:
- grunt test:teardown
env:
  global:
  #AWS_ACCESS_KEY_ID
  - secure: "ZJTT7faHhrpuzwDvgB/ctxLhnKVaOxB5LirysUw/C+hc6TnZrPwmGVlFVmJyWgMQVdkA/r7nlWsI7vZ05VVWIJ1i656uu6DIUhPyu+SAVWFw/5LK6yFQxABbWYI0a2if0P1GWM1bpAYSQM4vQ0pWIsInvp8nbvvXBPqQayvlMq4="
  #AWS_SECRET_ACCESS_KEY
  - secure: "c/V+hR9sZ5lQ8XkcRsxv+zTybIS2rhrB9D/O16h6kJHp7YB5AxQDt9tiVtcPE47G8FxY/aueljuBON3fIK3Z5JbkKKxQivULb0hmEzvw4S3ZYJunTrYDt616eQqV6OVx0ZHXdaWGuw+Y3Vk50Z0aYdHPCoI+Gw6SE7TwYekSHQE="
  #USERNAME_28
  - secure: "R2wc9nzyq3SugTxSfAuQ9d5+tbVC3/svFlDeLkJy3+gioW+XjNg8JhAbFn8c2UEjoHV6NAlBM2mldDGitBiOZpL+qtG1PperVjnyjwqaYGVJRV6SPnUh+UhSBRv3APV8nxyFWjide7WmQXlkoPzTXAlIiRudCX45xVofvgkdGi8="
  #PASSWORD_28
  - secure: "AwbHQZSyjgcJyVIwIQZhFedWhTbFUBjCb5a3QFbvZjol28EI+E0bfJI/cPWxXXGmPer3es+YvkOMuotQ77umV1QwCIH5Mt1tqvXv4ePzuWyWrtP+dYCXhfrRYVOdqrXXUosYXrR204QVG71yq4ga5/LFLp//odiyIu5gZETWcJ4="
  #USERNAME_XBRL_DB
  - secure: "MfHSYxbkpvS3SkupCm1dhUjn36YdmghsomD245DpLIMFDhiZ3OVeCsNYio+5jmOFIYRgvYUoxMjyAaguFVw9ELxVdhIHzkwh5t8iXz64R/vLnLX9Jj0GxSvUUYoRoXLvZ5KTCGp8k0ZWudUBiBycBs8IBG6k0NuQUQ6goH8tBbo="
  #PASSWORD_XBRL_DB
  - secure: "UQcOf01FqmNOcuMVSbKNotJwaMnoa5ZgqD8Xfp16pJxt+XOjuXNcfcytu1O02h+7cyJQeDi2XNL6IFbx5t2/RV+3bgg6nSM0FpiQCbwpAF2wFrfqzGdJhMHHsvceDJb3xQAZDhmPggq/4jhxJIXj0erE1yOpQuFFPcojFGeRMEA="
  #NAME_XBRL_DB
  - secure: "DkgU5/7nBg7UDmmWQuhfFF1xpzmj6H1x4vYmiKH4MGqGD2pptJEfC0fnmn2ktlHHGSqSP4KRZbg8twNPK06pVAajpFaT+5w4Jj8M1AHxkwdL33mnLqBUYHru/MnLcINfTmRwAQx9UaYkhplr1TQyyvckajU26HnJZiBa79CxpPM="