language: node_js
node_js:
- '0.10'
before_script:
- npm install -g bower
- bower install
- npm install -g grunt-cli
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
# setup/deploy for ci or only deploy to prod if on master
- grunt test:setup
# run tests against deployed version
- grunt test:run
after_script:
# teardown will work only for ci not for prod or on master
- grunt test:teardown --verbose
env:
  global:
  - RANDOM_ID=$RANDOM
  #TRAVIS_SECRET_KEY
  - secure: fiUFTXfxErtySuib70NOP40NJ9D15ArwkZmkZhjoHP0fpTcLvhi0AuvEEDuGrsn+Cs35vFcuQlflarP+1e/5LMe4jUaGXuhBtUUcf9d1znpJHBgpHuj+jEHFCoQ3ew+NXrh+lKADKeyalkF8R9xXjj/+dwfNVWVu8n85qw0mn/I=
notifications:
  hipchat:
    rooms:
      secure: DAadQPz4vBFwygNQk0yqqdWqRy9huP0hnxpF6SzMNAyEtje6s/5JdOn/KHLNNd8wvC6lQjaBY6Ano2vNKwEn3NJFbpDaBebs/Xh92CnME2oaiAovY/ml5Ob3bWSCuS9KC7+UQKg++IwRIUHLQyfv6SuDzrBeXCyqmTQ0FpW9RPg=
